### ISSUE TITLE
$issue_token, and $cookies seemed not working anymore

### ISSUE THREAD

**Issue by rolandbreedveld** [gboudreau/nest-api#141]
Working for a long time with this, sometimes had to recreate the $issue_token, and $cookies, without problems
but since a couple of week, it's not accepting the new values anymore:

PHP Notice:  Undefined variable: result in /home/pi/nest-api/nest.class.php on line 1295
PHP Fatal error:  Uncaught UnexpectedValueException: Response to login request doesn't contain required access token. Response: null in /home/pi/nest-api/nest.class.php:1295
Stack trace:
#0 /home/pi/nest-api/nest.class.php(1290): Nest->login(false)
#1 /home/pi/nest-api/nest.class.php(124): Nest->login()
#2 /home/pi/nest-api/get_nest.php(20): Nest->__construct(NULL, NULL, 'https://account...', '__Secure-3PSID=...')
#3 {main}
  thrown in /home/pi/nest-api/nest.class.php on line 1295

hope someone solved this,
regards, Roland

**Comment by newadventure079** [comment]
I'm seeing the exact same thing too

**Comment by rolandbreedveld** [comment]
Solved the issue, if you use (as I did) the the value copy button in chrome it will translate all stuf like %20 to a space, when I copied the string (not with the button, everything works again.
Think this is changed this behaviour in the latest Chrome releases.

**Comment by remcohans** [comment]
I noticed this problem too but it seems to be related to something else then the filled in values. an exact copy does not run on my raspberry but does run on quickly setup ubuntu vm. I guess there is a version problem with something else. Did anyone else run into this and already found the culprit?
